=== ollierob/Ramify/data/xml/src/main/resources/xml/schema/schema1.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:ns1="http://ramify.net/dates"
        xmlns:tns="http://ramify.net/places"
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://ramify.net/places"
        version="1.0">

    <import namespace="http://ramify.net/dates" schemaLocation="schema2.xsd"/>

    <element name="alsoSee" type="tns:xmlAlsoSeeId"/>

    <element name="chapelry" type="tns:xmlChapelry"/>

    <element name="church" type="tns:xmlChurch"/>

    <element name="churchInfo" type="tns:xmlChurchInfo"/>

    <element name="churchInfos" type="tns:churchInfos"/>

    <element name="churchRecordSet" type="tns:xmlChurchRecordSetInfo"/>

    <element name="country" type="tns:xmlCountry"/>

    <element name="county" type="tns:xmlCounty"/>

    <element name="farmstead" type="tns:xmlFarmstead"/>

    <element name="graveship" type="tns:xmlGraveship"/>

    <element name="hamlet" type="tns:xmlHamlet"/>

    <element name="manor" type="tns:xmlManor"/>

    <element name="parish" type="tns:xmlParish"/>

    <element name="placeDescription" type="tns:xmlPlaceDescription"/>

    <element name="placeDescriptions" type="tns:placeDescriptions"/>

    <element name="placePoint" type="tns:xmlPlacePoint"/>

    <element name="placePositions" type="tns:placePositions"/>

    <element name="places" type="tns:places"/>

    <element name="state" type="tns:xmlState"/>

    <element name="town" type="tns:xmlTown"/>

    <element name="township" type="tns:xmlTownship"/>

    <element name="village" type="tns:xmlVillage"/>

    <element name="wikipediaLink" type="tns:xmlWikipediaLink"/>

    <complexType name="xmlChurchInfo">

        <sequence>

            <choice minOccurs="0">

                <element ref="ns1:foundedBefore"/>

                <element ref="ns1:foundedIn"/>

            </choice>

            <choice minOccurs="0">

                <element ref="ns1:closedBefore"/>

                <element ref="ns1:closedIn"/>

            </choice>

            <element maxOccurs="unbounded" minOccurs="0" ref="tns:churchRecordSet"/>

        </sequence>

        <attribute name="id" type="xs:string" use="required"/>

        <attribute name="denomination" type="xs:string"/>

    </complexType>

    <complexType name="xmlChurchRecordSetInfo">

        <simpleContent>

            <extension base="xs:string">

                <attribute name="id" type="xs:string" use="required"/>

                <attribute name="type" type="tns:type" use="required"/>

                <attribute name="startYear" type="xs:int" use="required"/>

                <attribute name="endYear" type="xs:int" use="required"/>

            </extension>

        </simpleContent>

    </complexType>

    <complexType name="churchInfos">

        <sequence>

            <element maxOccurs="unbounded" minOccurs="0" ref="tns:churchInfo"/>

        </sequence>

    </complexType>

    <complexType name="xmlAlsoSeeId">

        <sequence/>

        <attribute name="id" type="xs:string" use="required"/>

    </complexType>

    <complexType abstract="true" name="xmlLink">

        <sequence/>

        <attribute name="href" type="xs:string" use="required"/>

    </complexType>

    <complexType name="xmlWikipediaLink">

        <complexContent>

            <extension base="tns:xmlLink">

                <sequence/>

            </extension>

        </complexContent>

    </complexType>

    <complexType name="xmlPlaceDescription">

        <sequence>

            <element maxOccurs="unbounded" minOccurs="0" ref="tns:alsoSee"/>

            <element maxOccurs="unbounded" minOccurs="0" ref="tns:wikipediaLink"/>

            <element form="qualified" name="description" type="xs:string"/>

        </sequence>

        <attribute name="id" type="xs:string" use="required"/>

    </complexType>

    <complexType name="placeDescriptions">

        <sequence>

            <element maxOccurs="unbounded" minOccurs="0" ref="tns:placeDescription"/>

        </sequence>

    </complexType>

    <complexType name="xmlPlacePoint">

        <sequence/>

        <attribute name="id" type="xs:string" use="required"/>

        <attribute name="latitude" type="xs:double" use="required"/>

        <attribute name="longitude" type="xs:double" use="required"/>

        <attribute name="zoom" type="xs:int"/>

    </complexType>

    <complexType name="placePositions">

        <sequence>

            <element maxOccurs="unbounded" minOccurs="0" ref="tns:placePoint"/>

        </sequence>

    </complexType>

    <complexType name="xmlChapelry">

        <complexContent>

            <extension base="tns:xmlPlace">

                <sequence>

                    <choice maxOccurs="unbounded" minOccurs="0">

                        <element ref="tns:township"/>

                        <element ref="tns:town"/>

                        <element ref="tns:village"/>

                        <element ref="tns:church"/>

                    </choice>

                </sequence>

            </extension>

        </complexContent>

    </complexType>

    <complexType abstract="true" name="xmlPlace">

        <sequence/>

        <attribute name="id" type="xs:string" use="required"/>

        <attribute name="name" type="xs:string"/>

    </complexType>

    <complexType name="xmlTownship">

        <complexContent>

            <extension base="tns:xmlPlace">

                <sequence>

                    <choice maxOccurs="unbounded" minOccurs="0">

                        <element ref="tns:village"/>

                        <element ref="tns:hamlet"/>

                        <element ref="tns:church"/>

                        <element ref="tns:farmstead"/>

                    </choice>

                </sequence>

            </extension>

        </complexContent>

    </complexType>

    <complexType name="xmlVillage">

        <complexContent>

            <extension base="tns:xmlPlace">

                <sequence>

                    <element maxOccurs="unbounded" minOccurs="0" ref="tns:church"/>

                </sequence>

            </extension>

        </complexContent>

    </complexType>

    <complexType name="xmlChurch">

        <complexContent>

            <extension base="tns:xmlPlace">

                <sequence/>

            </extension>

        </complexContent>

    </complexType>

    <complexType name="xmlCountry">

        <complexContent>

            <extension base="tns:xmlPlace">

                <sequence>

                    <choice maxOccurs="unbounded" minOccurs="0">

                        <element ref="tns:country"/>

                        <element ref="tns:county"/>

                        <element ref="tns:state"/>

                    </choice>

                </sequence>

            </extension>

        </complexContent>

    </complexType>

    <complexType name="xmlCounty">

        <complexContent>

            <extension base="tns:xmlPlace">

                <sequence>

                    <choice maxOccurs="unbounded" minOccurs="0">

                        <element ref="tns:parish"/>

                        <element ref="tns:manor"/>

                    </choice>

                </sequence>

            </extension>

        </complexContent>

    </complexType>

    <complexType name="xmlParish">

        <complexContent>

            <extension base="tns:xmlPlace">

                <sequence>

                    <choice maxOccurs="unbounded" minOccurs="0">

                        <element ref="tns:parish"/>

                        <element ref="tns:chapelry"/>

                        <element ref="tns:township"/>

                        <element ref="tns:town"/>

                        <element ref="tns:village"/>

                    </choice>

                </sequence>

            </extension>

        </complexContent>

    </complexType>

    <complexType name="xmlTown">

        <complexContent>

            <extension base="tns:xmlPlace">

                <sequence>

                    <element maxOccurs="unbounded" minOccurs="0" ref="tns:church"/>

                </sequence>

            </extension>

        </complexContent>

    </complexType>

    <complexType name="xmlManor">

        <complexContent>

            <extension base="tns:xmlPlace">

                <sequence>

                    <choice maxOccurs="unbounded" minOccurs="0">

                        <element ref="tns:manor"/>

                        <element ref="tns:graveship"/>

                    </choice>

                </sequence>

            </extension>

        </complexContent>

    </complexType>

    <complexType name="xmlGraveship">

        <complexContent>

            <extension base="tns:xmlPlace">

                <sequence>

                    <element maxOccurs="unbounded" minOccurs="0" ref="tns:manor"/>

                </sequence>

            </extension>

        </complexContent>

    </complexType>

    <complexType name="xmlState">

        <complexContent>

            <extension base="tns:xmlPlace">

                <sequence/>

            </extension>

        </complexContent>

    </complexType>

    <complexType name="xmlHamlet">

        <complexContent>

            <extension base="tns:xmlPlace">

                <sequence>

                    <choice maxOccurs="unbounded" minOccurs="0">

                        <element ref="tns:church"/>

                        <element ref="tns:farmstead"/>

                    </choice>

                </sequence>

            </extension>

        </complexContent>

    </complexType>

    <complexType name="xmlFarmstead">

        <complexContent>

            <extension base="tns:xmlPlace">

                <sequence/>

            </extension>

        </complexContent>

    </complexType>

    <complexType name="places">

        <sequence>

            <choice maxOccurs="unbounded" minOccurs="0">

                <element ref="tns:chapelry"/>

                <element ref="tns:township"/>

                <element ref="tns:village"/>

                <element ref="tns:church"/>

                <element ref="tns:country"/>

                <element ref="tns:county"/>

                <element ref="tns:parish"/>

                <element ref="tns:town"/>

                <element ref="tns:manor"/>

                <element ref="tns:graveship"/>

                <element ref="tns:state"/>

                <element ref="tns:hamlet"/>

                <element ref="tns:farmstead"/>

            </choice>

        </sequence>

    </complexType>

    <simpleType name="type">

        <restriction base="xs:string">

            <enumeration value="baptism"/>

            <enumeration value="birth"/>

            <enumeration value="membership"/>

            <enumeration value="marriage"/>

            <enumeration value="burial"/>

            <enumeration value="pewRents"/>

            <enumeration value="accounts"/>

            <enumeration value="minutes"/>

        </restriction>

    </simpleType>

</schema>

=== ollierob/Ramify/data/xml/src/main/resources/xml/data/england/west_yorkshire/heptonstall/1-heptonstall.xml
<?xml version="1.0" encoding="UTF-8" ?>

<places
        xmlns="http://ramify.net/places"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://ramify.net/places ../../../../schema/schema1.xsd">

    <township id="heptonstall">

        <village id="heptonstall" name="Heptonstall">

            <church id="heptonstall-st-thomas" name="St Thomas"/>
            <church id="heptonstall-wesleyan" name="Heptonstall Methodist"/>

        </village>

        <hamlet id="slack" name="Slack">

            <church id="slack-mt-zion" name="Mount Zion"/>
            <farmstead id="robertshaw" name="Robertshaw"/>

        </hamlet>

    </township>

</places>

=== ollierob/Ramify/data/xml/src/main/resources/xml/data/england/west_yorkshire/heptonstall/0-townships.xml
<?xml version="1.0" encoding="UTF-8" ?>

<places
        xmlns="http://ramify.net/places"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://ramify.net/places ../../../../schema/schema1.xsd">

    <parish id="heptonstall">
        <township id="heptonstall" name="Heptonstall"/>
        <township id="erringden" name="Erringden"/>
        <township id="stansfield" name="Stansfield"/>
        <township id="langfield" name="Langfield"/>
        <township id="wadsworth" name="Wadsworth"/>
        <town id="hebden_bridge" name="Hebden Bridge"/>
        <town id="todmorden" name="Todmorden"/>
    </parish>

</places>

=== ollierob/Ramify/data/xml/src/main/resources/xml/data/england/west_yorkshire/1-manor.xml
<?xml version="1.0" encoding="UTF-8" ?>

<places
        xmlns="http://ramify.net/places"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://ramify.net/places ../../../schema/schema1.xsd">

    <county id="west_yorkshire">

        <manor id="wakefield" name="Wakefield">

            <manor id="halifax" name="Halifax"/>
            <manor id="heptonstall" name="Heptonstall"/>
            <manor id="stansfield" name="Stansfield"/>
            <manor id="wadsworth" name="Wadsworth"/>

        </manor>

        <manor id="pontefract" name="Honour of Pontefract">

        </manor>

    </county>

</places>

=== ollierob/Ramify/data/xml/src/main/resources/xml/data/england/west_yorkshire/heptonstall/1-heptonstall-descriptions.xml
<?xml version="1.0" encoding="UTF-8" ?>

<placeDescriptions
        xmlns="http://ramify.net/places"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://ramify.net/places ../../../../schema/schema1.xsd">

    <placeDescription id="township:heptonstall">
        <alsoSee id="township:stansfield"/>
        <alsoSee id="township:wadsworth"/>
        <alsoSee id="township:erringden"/>
        <alsoSee id="township:langfield"/>
        <wikipediaLink href="en.wikipedia.org/wiki/Heptonstall"/>
        <description>
            Heptonstall township, centered on the village, encompassed part of Hebden Bridge and the lands along Widdop
            road and Edge Lane. Its border with Stansfield township lay along the Colden Water.
        </description>
    </placeDescription>

    <placeDescription id="village:heptonstall">
        <alsoSee id="town:hebden_bridge"/>
        <description>
            The village of Heptonstall sits on the hilltop above Hebden Bridge.
            First mentioned in the 13th century, it formed part of the *rectorial* manor of Halifax-cum-Heptonstall.
        </description>
    </placeDescription>

    <placeDescription id="church:heptonstall-st-thomas">
        <description>
            St Thomas church was built before 1260 and dedicated to St Thomas a Becket, the Archbishop of Canterbury
            who was murdered in 1170.

            In 1847 a storm tore off some of the roof and part of the tower collapsed.
            It was decided that a new church should be built, and a new church dedicated to St Thomas the Apostle was
            consecrated in 1854.
        </description>
    </placeDescription>

    <placeDescription id="church:slack-mt-zion">
        <alsoSee id="church:birchcliffe"/>
        <description>
            Mount Zion was founded by former members of Birchcliffe, who were upset at the ordination of a new minister.
        </description>
    </placeDescription>

    <placeDescription id="farmstead:robertshaw">
        <alsoSee id="farmstead:learings"/>
        <description>
            Robertshaw was first named in a rental for Halifax-cum-Heptonstall manor dated 1429.
        </description>
    </placeDescription>

</placeDescriptions>

=== ollierob/Ramify/data/xml/src/main/resources/xml/data/england/west_yorkshire/heptonstall/4-stansfield.xml
<places
        xmlns="http://ramify.net/places"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://ramify.net/places ../../../../schema/schema1.xsd">

    <township id="stansfield">

        <church id="cross_stone" name="St Pauls"/>

        <hamlet id="eastwood" name="Eastwood"/>
        <church id="eastwood" name="Eastwood"/>

        <hamlet id="shore" name="Shore"/>
        <church id="shore" name="Shore"/>

    </township>

    <town id="todmorden">

        <church id="roomfield" name="Roomfield"/>

    </town>

</places>

=== ollierob/Ramify/data/xml/src/main/resources/xml/data/england/west_yorkshire/heptonstall/3-wadsworth.xml
<places
        xmlns="http://ramify.net/places"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://ramify.net/places ../../../../schema/schema1.xsd">

    <township id="wadsworth">

        <church id="wainsgate" name="Wainsgate"/>

        <hamlet id="old_town" name="Old Town"/>

        <hamlet id="shackleton" name="Shackleton"/>

        <village id="pecket_well" name="Pecket Well">
            <church id="crimsworth" name="Crimsworth"/>
        </village>

        <church id="crimsworth_dean" name="Crimsworth Dean"/>

        <farmstead id="high_hirst" name="High Hirst"/>

        <hamlet id="widdop" name="Widdop">
            <farmstead id="lower_houses" name="Lower Houses"/>
            <farmstead id="higher_houses" name="Higher Houses"/>
        </hamlet>

        <hamlet id="walshaw" name="Walshaw"/>

    </township>

</places>

=== ollierob/Ramify/data/xml/src/main/resources/xml/data/england/west_yorkshire/heptonstall/1-heptonstall-locations.xml
<?xml version="1.0" encoding="UTF-8" ?>

<placePositions
        xmlns="http://ramify.net/places"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://ramify.net/places ../../../../schema/schema1.xsd">

    <placePoint id="chapelry:heptonstall" latitude="53.737632" longitude="-2.071990" zoom="11"/>
    <placePoint id="township:heptonstall" latitude="53.754719" longitude="-2.037193" zoom="12"/>
    <placePoint id="village:heptonstall" latitude="53.748845" longitude="-2.021594" zoom="14"/>
    <placePoint id="church:heptonstall-st-thomas" latitude="53.748845" longitude="-2.021594"/>
    <placePoint id="school:heptonstall_grammar" latitude="53.74888" longitude="-2.02118" zoom="16"/>

    <placePoint id="church:slack-mt-zion" latitude="53.75484" longitude="-2.03663"/>
    <placePoint id="farmstead:robertshaw" latitude="53.75427" longitude="-2.03458"/>

</placePositions>

=== ollierob/Ramify/data/xml/src/main/resources/xml/data/england/west_yorkshire/heptonstall/locations.xml
<?xml version="1.0" encoding="UTF-8" ?>

<placePositions
        xmlns="http://ramify.net/places"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://ramify.net/places ../../../../schema/schema1.xsd">

    <placePoint id="town:hebden_bridge" latitude="53.742" longitude="-2.009"/>

    <placePoint id="chapelry:heptonstall" latitude="53.737632" longitude="-2.071990"/>
    <placePoint id="township:heptonstall" latitude="53.754719" longitude="-2.037193"/>
    <placePoint id="village:heptonstall" latitude="53.748845" longitude="-2.021594"/>
    <placePoint id="church:heptonstall-st-thomas" latitude="53.748845" longitude="-2.021594"/>

    <placePoint id="church:slack-mt-zion" latitude="53.75484" longitude="-2.03663"/>
    <placePoint id="farmstead:robertshaw" latitude="53.75427" longitude="-2.03458"/>

    <placePoint id="church:shore" latitude="53.73595" longitude="-2.1314"/>

</placePositions>
