=== ollierob/Ramify/server/xml/src/main/resources/xml/schema/places.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:ns1="http://ramify.net/dates"
        xmlns:tns="http://ramify.net/places"
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://ramify.net/places"
        version="1.0">

    <import namespace="http://ramify.net/dates" schemaLocation="dates.xsd"/>

    <element name="alsoSee" type="tns:xmlAlsoSeeId"/>

    <element name="archive" type="tns:xmlArchive"/>

    <element name="archives" type="tns:archives"/>

    <element name="chapelry" type="tns:xmlChapelry"/>

    <element name="church" type="tns:xmlChurch"/>

    <element name="churchInfo" type="tns:xmlChurchInfo"/>

    <element name="churchInfos" type="tns:churchInfos"/>

    <element name="churchRecordSet" type="tns:xmlChurchRecordSetInfo"/>

    <element name="country" type="tns:xmlCountry"/>

    <element name="county" type="tns:xmlCounty"/>

    <element name="farmstead" type="tns:xmlFarmstead"/>

    <element name="graveship" type="tns:xmlGraveship"/>

    <element name="graveyard" type="tns:xmlGraveyard"/>

    <element name="hamlet" type="tns:xmlHamlet"/>

    <element name="inn" type="tns:xmlInn"/>

    <element name="manor" type="tns:xmlManor"/>

    <element name="mill" type="tns:xmlMill"/>

    <element name="nationalArchivesLink" type="tns:xmlNationalArchivesLink"/>

    <element name="parish" type="tns:xmlParish"/>

    <element name="placeDescription" type="tns:xmlPlaceDescription"/>

    <element name="placeDescriptions" type="tns:placeDescriptions"/>

    <element name="placePoint" type="tns:xmlPlacePoint"/>

    <element name="placePositions" type="tns:placePositions"/>

    <element name="places" type="tns:places"/>

    <element name="school" type="tns:xmlSchool"/>

    <element name="state" type="tns:xmlState"/>

    <element name="street" type="tns:xmlStreet"/>

    <element name="textLink" type="tns:xmlTextLink"/>

    <element name="town" type="tns:xmlTown"/>

    <element name="township" type="tns:xmlTownship"/>

    <element name="village" type="tns:xmlVillage"/>

    <element name="wapentake" type="tns:xmlWapentake"/>

    <element name="wikipediaLink" type="tns:xmlWikipediaLink"/>

    <complexType name="xmlArchive">

        <sequence>

            <element form="qualified" minOccurs="0" name="description" type="xs:string"/>

            <element minOccurs="0" ref="tns:textLink"/>

        </sequence>

        <attribute name="id" type="xs:string" use="required"/>

        <attribute name="name" type="xs:string" use="required"/>

        <attribute name="iconHref" type="xs:string"/>

    </complexType>

    <complexType name="xmlTextLink">

        <complexContent>

            <extension base="tns:xmlLink">

                <sequence/>

                <attribute name="text" type="xs:string" use="required"/>

            </extension>

        </complexContent>

    </complexType>

    <complexType abstract="true" name="xmlLink">

        <sequence/>

        <attribute name="href" type="xs:string" use="required"/>

    </complexType>

    <complexType name="xmlWikipediaLink">

        <complexContent>

            <extension base="tns:xmlLink">

                <sequence/>

            </extension>

        </complexContent>

    </complexType>

    <complexType name="xmlNationalArchivesLink">

        <complexContent>

            <extension base="tns:xmlLink">

                <sequence/>

            </extension>

        </complexContent>

    </complexType>

    <complexType name="archives">

        <sequence>

            <element maxOccurs="unbounded" minOccurs="0" ref="tns:archive"/>

        </sequence>

    </complexType>

    <complexType name="xmlChurchInfo">

        <sequence>

            <choice minOccurs="0">

                <element ref="ns1:foundedBefore"/>

                <element ref="ns1:foundedIn"/>

            </choice>

            <choice minOccurs="0">

                <element ref="ns1:closedBefore"/>

                <element ref="ns1:closedIn"/>

            </choice>

            <element maxOccurs="unbounded" minOccurs="0" ref="tns:churchRecordSet"/>

        </sequence>

        <attribute name="id" type="xs:string" use="required"/>

        <attribute name="denomination" type="xs:string"/>

    </complexType>

    <complexType name="xmlChurchRecordSetInfo">

        <sequence/>

        <attribute name="id" type="xs:string" use="required"/>

    </complexType>

    <complexType name="churchInfos">

        <sequence>

            <element maxOccurs="unbounded" minOccurs="0" ref="tns:churchInfo"/>

        </sequence>

    </complexType>

    <complexType name="xmlAlsoSeeId">

        <sequence/>

        <attribute name="id" type="xs:string" use="required"/>

    </complexType>

    <complexType name="xmlPlaceDescription">

        <sequence>

            <element maxOccurs="unbounded" minOccurs="0" ref="tns:alsoSee"/>

            <choice maxOccurs="unbounded" minOccurs="0">

                <element ref="tns:textLink"/>

                <element ref="tns:wikipediaLink"/>

                <element ref="tns:nationalArchivesLink"/>

            </choice>

            <element form="qualified" name="description" type="xs:string"/>

        </sequence>

        <attribute name="id" type="xs:string" use="required"/>

    </complexType>

    <complexType name="placeDescriptions">

        <sequence>

            <element maxOccurs="unbounded" minOccurs="0" ref="tns:placeDescription"/>

        </sequence>

    </complexType>

    <complexType name="xmlPlacePoint">

        <sequence/>

        <attribute name="id" type="xs:string" use="required"/>

        <attribute name="latitude" type="xs:double" use="required"/>

        <attribute name="longitude" type="xs:double" use="required"/>

        <attribute name="zoom" type="xs:int"/>

    </complexType>

    <complexType name="placePositions">

        <sequence>

            <element maxOccurs="unbounded" minOccurs="0" ref="tns:placePoint"/>

        </sequence>

    </complexType>

    <complexType abstract="true" name="xmlPlace">

        <sequence/>

        <attribute name="id" type="xs:string" use="required"/>

        <attribute name="name" type="xs:string"/>

    </complexType>

    <complexType name="xmlCountry">

        <complexContent>

            <extension base="tns:xmlPlace">

                <sequence>

                    <choice maxOccurs="unbounded" minOccurs="0">

                        <element ref="tns:country"/>

                        <element ref="tns:county"/>

                        <element ref="tns:state"/>

                    </choice>

                </sequence>

                <attribute name="iso" type="xs:string" use="required"/>

            </extension>

        </complexContent>

    </complexType>

    <complexType name="xmlCounty">

        <complexContent>

            <extension base="tns:xmlPlace">

                <sequence>

                    <choice maxOccurs="unbounded" minOccurs="0">

                        <element ref="tns:parish"/>

                        <element ref="tns:manor"/>

                        <element ref="tns:wapentake"/>

                    </choice>

                </sequence>

                <attribute name="iso" type="xs:string"/>

            </extension>

        </complexContent>

    </complexType>

    <complexType name="xmlParish">

        <complexContent>

            <extension base="tns:xmlPlace">

                <sequence>

                    <choice maxOccurs="unbounded" minOccurs="0">

                        <element ref="tns:parish"/>

                        <element ref="tns:chapelry"/>

                        <element ref="tns:township"/>

                        <element ref="tns:town"/>

                        <element ref="tns:village"/>

                    </choice>

                </sequence>

            </extension>

        </complexContent>

    </complexType>

    <complexType name="xmlChapelry">

        <complexContent>

            <extension base="tns:xmlPlace">

                <sequence>

                    <choice maxOccurs="unbounded" minOccurs="0">

                        <element ref="tns:township"/>

                        <element ref="tns:town"/>

                        <element ref="tns:village"/>

                        <element ref="tns:church"/>

                        <element ref="tns:school"/>

                    </choice>

                </sequence>

            </extension>

        </complexContent>

    </complexType>

    <complexType name="xmlTownship">

        <complexContent>

            <extension base="tns:xmlPlace">

                <sequence>

                    <choice maxOccurs="unbounded" minOccurs="0">

                        <element ref="tns:village"/>

                        <element ref="tns:hamlet"/>

                        <element ref="tns:church"/>

                        <element ref="tns:school"/>

                        <element ref="tns:farmstead"/>

                        <element ref="tns:mill"/>

                        <element ref="tns:inn"/>

                    </choice>

                </sequence>

            </extension>

        </complexContent>

    </complexType>

    <complexType name="xmlVillage">

        <complexContent>

            <extension base="tns:xmlPlace">

                <sequence>

                    <choice maxOccurs="unbounded" minOccurs="0">

                        <element ref="tns:street"/>

                        <element ref="tns:church"/>

                        <element ref="tns:mill"/>

                        <element ref="tns:school"/>

                        <element ref="tns:inn"/>

                        <element ref="tns:graveyard"/>

                    </choice>

                </sequence>

            </extension>

        </complexContent>

    </complexType>

    <complexType name="xmlStreet">

        <complexContent>

            <extension base="tns:xmlPlace">

                <sequence/>

            </extension>

        </complexContent>

    </complexType>

    <complexType name="xmlChurch">

        <complexContent>

            <extension base="tns:xmlPlace">

                <sequence/>

            </extension>

        </complexContent>

    </complexType>

    <complexType name="xmlMill">

        <complexContent>

            <extension base="tns:xmlPlace">

                <sequence/>

            </extension>

        </complexContent>

    </complexType>

    <complexType name="xmlSchool">

        <complexContent>

            <extension base="tns:xmlPlace">

                <sequence/>

            </extension>

        </complexContent>

    </complexType>

    <complexType name="xmlInn">

        <complexContent>

            <extension base="tns:xmlPlace">

                <sequence/>

            </extension>

        </complexContent>

    </complexType>

    <complexType name="xmlGraveyard">

        <complexContent>

            <extension base="tns:xmlPlace">

                <sequence/>

            </extension>

        </complexContent>

    </complexType>

    <complexType name="xmlHamlet">

        <complexContent>

            <extension base="tns:xmlPlace">

                <sequence>

                    <choice maxOccurs="unbounded" minOccurs="0">

                        <element ref="tns:church"/>

                        <element ref="tns:mill"/>

                        <element ref="tns:inn"/>

                        <element ref="tns:farmstead"/>

                    </choice>

                </sequence>

            </extension>

        </complexContent>

    </complexType>

    <complexType name="xmlFarmstead">

        <complexContent>

            <extension base="tns:xmlPlace">

                <sequence/>

            </extension>

        </complexContent>

    </complexType>

    <complexType name="xmlTown">

        <complexContent>

            <extension base="tns:xmlPlace">

                <sequence>

                    <choice maxOccurs="unbounded" minOccurs="0">

                        <element ref="tns:street"/>

                        <element ref="tns:church"/>

                        <element ref="tns:mill"/>

                        <element ref="tns:school"/>

                        <element ref="tns:inn"/>

                        <element ref="tns:graveyard"/>

                    </choice>

                </sequence>

            </extension>

        </complexContent>

    </complexType>

    <complexType name="xmlManor">

        <complexContent>

            <extension base="tns:xmlPlace">

                <sequence>

                    <choice maxOccurs="unbounded" minOccurs="0">

                        <element ref="tns:manor"/>

                        <element ref="tns:graveship"/>

                    </choice>

                </sequence>

            </extension>

        </complexContent>

    </complexType>

    <complexType name="xmlGraveship">

        <complexContent>

            <extension base="tns:xmlPlace">

                <sequence>

                    <element maxOccurs="unbounded" minOccurs="0" ref="tns:manor"/>

                </sequence>

            </extension>

        </complexContent>

    </complexType>

    <complexType name="xmlWapentake">

        <complexContent>

            <extension base="tns:xmlPlace">

                <sequence>

                    <choice maxOccurs="unbounded" minOccurs="0">

                        <element ref="tns:parish"/>

                        <element ref="tns:manor"/>

                    </choice>

                </sequence>

            </extension>

        </complexContent>

    </complexType>

    <complexType name="xmlState">

        <complexContent>

            <extension base="tns:xmlPlace">

                <sequence/>

            </extension>

        </complexContent>

    </complexType>

    <complexType name="places">

        <sequence>

            <choice maxOccurs="unbounded" minOccurs="0">

                <element ref="tns:country"/>

                <element ref="tns:county"/>

                <element ref="tns:parish"/>

                <element ref="tns:chapelry"/>

                <element ref="tns:township"/>

                <element ref="tns:village"/>

                <element ref="tns:street"/>

                <element ref="tns:church"/>

                <element ref="tns:mill"/>

                <element ref="tns:school"/>

                <element ref="tns:inn"/>

                <element ref="tns:graveyard"/>

                <element ref="tns:hamlet"/>

                <element ref="tns:farmstead"/>

                <element ref="tns:town"/>

                <element ref="tns:manor"/>

                <element ref="tns:graveship"/>

                <element ref="tns:wapentake"/>

                <element ref="tns:state"/>

            </choice>

        </sequence>

    </complexType>

</schema>

=== ollierob/Ramify/server/xml/src/main/resources/xml/data/england/west_yorkshire/morley/heptonstall/1-heptonstall-descriptions.xml
<?xml version="1.0" encoding="UTF-8" ?>

<placeDescriptions
        xmlns="http://ramify.net/places"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://ramify.net/places ../../../../../schema/places.xsd">

    <placeDescription id="manor:heptonstall">
        <alsoSee id="chapelry:heptonstall"/>
        <alsoSee id="township:heptonstall"/>
        <alsoSee id="village:heptonstall"/>
        <description>
            Heptonstall manor was created when Halifax-cum-Heptonstall manor was split in 1626.
        </description>
    </placeDescription>

    <placeDescription id="township:heptonstall">
        <alsoSee id="township:stansfield"/>
        <alsoSee id="township:wadsworth"/>
        <alsoSee id="township:erringden"/>
        <alsoSee id="township:langfield"/>
        <alsoSee id="manor:heptonstall"/>
        <alsoSee id="chapelry:heptonstall"/>
        <description>
            Heptonstall township, centered on the village, encompassed part of Hebden Bridge and the lands along Widdop
            road and Edge Lane. Its border with Stansfield township lay along the Colden Water.
        </description>
    </placeDescription>

    <placeDescription id="village:heptonstall">
        <alsoSee id="town:hebden_bridge"/>
        <alsoSee id="township:heptonstall"/>
        <alsoSee id="manor:heptonstall"/>
        <wikipediaLink href="https://en.wikipedia.org/wiki/Heptonstall"/>
        <description>
            The village of Heptonstall sits on the hilltop above Hebden Bridge.
            First mentioned in the 13th century, it formed part of the *rectorial* manor of Halifax-cum-Heptonstall,
            with tithes and rental income due to the monks of the Priory of Lewes in Sussex.
        </description>
    </placeDescription>

    <placeDescription id="church:heptonstall_st-thomas">
        <description>
            St Thomas church was built before 1260 and dedicated to St Thomas a Becket, the Archbishop of Canterbury
            who was murdered in 1170.

            In 1847 a storm tore off some of the roof and part of the tower collapsed.
            It was decided that a new church should be built, and a new church dedicated to St Thomas the Apostle was
            consecrated in 1854.
        </description>
    </placeDescription>

    <placeDescription id="church:heptonstall_wesleyan">
        <description>
            Methodism in Heptonstall can trace its roots back to the 1740s, with the establishment of Darney Societies
            and visitations by the Wesley brothers.
            An octagonal church was built in 1764 and claims to be the oldest Methodist church still in use.
        </description>
    </placeDescription>

    <placeDescription id="church:slack-mt-zion">
        <alsoSee id="church:birchcliffe"/>
        <description>
            Mount Zion was founded by former members of Birchcliffe, who were upset at the ordination of a new minister.
        </description>
    </placeDescription>

    <placeDescription id="farmstead:robertshaw">
        <alsoSee id="farmstead:learings"/>
        <description>
            Robertshaw was first named in a rental for Halifax-cum-Heptonstall manor dated 1429.
        </description>
    </placeDescription>

    <placeDescription id="school:heptonstall_grammar">
        <description>
            A grammar school was founded at Heptonstall by the will of the Rev. Charles Greenwood, lord of the manor of
            Heptonstall, in 1642.
        </description>
    </placeDescription>

</placeDescriptions>

=== ollierob/Ramify/server/xml-data/src/main/resources/xml/data/england/west_yorkshire/0-wapentakes.xml
<?xml version="1.0" encoding="UTF-8" ?>

<places
        xmlns="http://ramify.net/places"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://ramify.net/places ../../../schema/places.xsd">

    <county id="west_yorkshire">

        <wapentake id="ewcross" name="Ewcross"/>
        <wapentake id="staincliffe_west" name="Staincliffe (West Division)"/>
        <wapentake id="staincliffe_east" name="Staincliffe (East Division)"/>
        <wapentake id="claro_lower" name="Claro (Lower Division)"/>
        <wapentake id="claro_upper" name="Claro (Upper Division)"/>
        <wapentake id="skyrack_lower" name="Skyrack (Lower Division)"/>
        <wapentake id="skyrack_upper" name="Skyrack (Upper Division)"/>
        <wapentake id="strafforth_lower" name="Strafforth and Tickhill (Lower Division)"/>
        <wapentake id="strafforth_upper" name="Strafforth and Tickhill (Upper Division)"/>
        <wapentake id="agbrigg" name="Agbrigg"/>
        <wapentake id="morley" name="Morley"/>
        <wapentake id="staincross" name="Staincross"/>
        <wapentake id="barkston_ash" name="Barkston Ash"/>
        <wapentake id="osgoldcross" name="Osgoldcross"/>

    </county>

</places>

=== ollierob/Ramify/data/xml/src/main/resources/xml/data/england/west_yorkshire/halifax/0-townships.xml
<?xml version="1.0" encoding="UTF-8" ?>

<places
        xmlns="http://ramify.net/places"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://ramify.net/places ../../../../schema/places.xsd">

    <parish id="halifax">

        <town id="halifax" name="Halifax"/>

        <township id="barkisland" name="Barkisland"/>
        <township id="elland" name="Elland cum Greetland"/>
        <township id="fixby" name="Fixby"/>
        <township id="hipperholme" name="Hipperholme cum Brighouse"/>
        <township id="midgley" name="Midgley"/>
        <township id="norland" name="Norland"/>
        <township id="ovenden" name="Ovenden"/>
        <township id="northowram" name="Northowram"/>
        <township id="southowram" name="Southowram"/>
        <township id="rastrick" name="Rastrick"/>
        <township id="rishworth" name="Rishworth"/>
        <township id="shelf" name="Shelf"/>
        <township id="skircoat" name="Skircoat"/>
        <township id="sowerby" name="Sowerby"/>
        <township id="soyland" name="Soyland"/>
        <township id="stainland" name="Stainland"/>
        <township id="warley" name="Warley"/>

    </parish>

</places>

=== ollierob/Ramify/server/xml-data/src/main/resources/xml/data/england/west_yorkshire/morley/heptonstall/1-heptonstall-locations.xml
<?xml version="1.0" encoding="UTF-8" ?>

<placePositions
        xmlns="http://ramify.net/places"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://ramify.net/places ../../../../../schema/places.xsd">

    <placePoint id="chapelry:heptonstall" latitude="53.737632" longitude="-2.071990" zoom="11"/>
    <placePoint id="township:heptonstall" latitude="53.754719" longitude="-2.037193" zoom="12"/>
    <placePoint id="manor:heptonstall" latitude="53.754719" longitude="-2.037193" zoom="12"/>
    <placePoint id="village:heptonstall" latitude="53.748845" longitude="-2.021594" zoom="15"/>
    <placePoint id="church:heptonstall_st-thomas" latitude="53.748845" longitude="-2.021594" zoom="16"/>
    <placePoint id="church:heptonstall_wesleyan" latitude="53.7498" longitude="-2.02008" zoom="16"/>
    <placePoint id="school:heptonstall_grammar" latitude="53.74888" longitude="-2.02118" zoom="16"/>
    <placePoint id="inn:union_cross" latitude="53.74922" longitude="-2.02083"/>
    <placePoint id="inn:white_lion" latitude="53.74931" longitude="-2.02121"/>

    <placePoint id="church:slack-mt-zion" latitude="53.75484" longitude="-2.03663"/>
    <placePoint id="farmstead:robertshaw" latitude="53.75427" longitude="-2.03458"/>

    <placePoint id="hamlet:colden" latitude="53.753" longitude="-2.057" zoom="15"/>

</placePositions>

=== ollierob/Ramify/server/xml/src/main/resources/xml/data/england/west_yorkshire/descriptions.xml
<?xml version="1.0" encoding="UTF-8" ?>

<placeDescriptions
        xmlns="http://ramify.net/places"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://ramify.net/places ../../../schema/places.xsd">

    <placeDescription id="county:west_yorkshire">
        <wikipediaLink href="https://en.wikipedia.org/wiki/West_Yorkshire"/>
        <description>West Yorkshire, formerly the West Riding of Yorkshire, ...</description>
    </placeDescription>

    <placeDescription id="manor:wakefield">
        <alsoSee id="manor:pontefract"/>
        <nationalArchivesLink href="https://discovery.nationalarchives.gov.uk/details/c/F244618"/>
        <wikipediaLink href="https://en.wikipedia.org/wiki/Wakefield"/>
        <description>
            The Manor of Wakefield was first mentioned in Domesday Book in 1086.
            Much of the manor was *in waste*, likely as a consequence of William's Harrying of the North.
        </description>
    </placeDescription>
    
    <placeDescription id="ruraldistrict:hepton">
        <alsoSee id="metropolitanborough:calderdale"/>
        <description>Hepton Rural District existed between 1894 - 1974.</description>
    </placeDescription>

</placeDescriptions>

=== ollierob/Ramify/data/xml/src/main/resources/xml/data/england/west_yorkshire/heptonstall/3-wadsworth-descriptions.xml
<?xml version="1.0" encoding="UTF-8" ?>

<placeDescriptions
        xmlns="http://ramify.net/places"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://ramify.net/places ../../../../schema/places.xsd">

    <placeDescription id="township:wadsworth">
        <alsoSee id="township:stansfield"/>
        <alsoSee id="township:heptonstall"/>
        <alsoSee id="township:erringden"/>
        <alsoSee id="township:langfield"/>
        <wikipediaLink href="en.wikipedia.org/wiki/Wadsworth,_West_Yorkshire"/>
        <description>
            Wadsworth township was recorded as *Wadesuurde* in Domesday Book.
            Its name derives from *Wada's worth* (lands).
        </description>
    </placeDescription>

</placeDescriptions>

=== ollierob/Ramify/data/xml/src/main/resources/xml/data/england/west_yorkshire/morley/heptonstall/4-stansfield.xml
<places
        xmlns="http://ramify.net/places"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://ramify.net/places ../../../../../schema/places.xsd">

    <township id="stansfield">

        <church id="cross_stone" name="St Pauls"/>

        <village id="blackshaw_head" name="Blackshaw Head">
            <church id="blackshaw_head_chapel" name="Blackshaw Head Chapel"/>
        </village>

        <hamlet id="eastwood" name="Eastwood">
            <church id="eastwood" name="Eastwood"/>
        </hamlet>

        <hamlet id="shore" name="Shore">
            <church id="shore" name="Shore"/>
            <farmstead id="parrock" name="Parrock"/>
            <farmstead id="west_bar" name="West Bar"/>
        </hamlet>

        <hamlet id="rawtonstall" name="Rawtonstall"/>

    </township>

    <town id="todmorden">

        <church id="roomfield" name="Roomfield"/>
        <church id="patmos" name="Patmos"/>

    </town>

</places>

=== ollierob/Ramify/server/xml-data/src/main/resources/xml/data/england/west_yorkshire/1-wakefield-manor.xml
<?xml version="1.0" encoding="UTF-8" ?>

<places
        xmlns="http://ramify.net/places"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://ramify.net/places ../../../schema/places.xsd">

    <county id="west_yorkshire">

        <manor id="wakefield" name="Wakefield">

            <graveship id="holme" name="Holme"/>

            <graveship id="sowerby" name="Sowerby">

                <manor id="halifax" name="Halifax"/>
                <manor id="midgley" name="Midgley"/>
                <manor id="sowerby" name="Sowerby"/>
                <manor id="warley" name="Warley"/>
                <manor id="ovenden" name="Ovenden"/>

                <manor id="heptonstall" name="Heptonstall"/>
                <manor id="langfield" name="Langfield"/>
                <manor id="stansfield" name="Stansfield"/>
                <manor id="wadsworth" name="Wadsworth"/>

            </graveship>

            <graveship id="wakefield" name="Wakefield"/>

        </manor>

    </county>

</places>
